FROM ruby:3.1.2-alpine3.16

# install the build essential tools to compile the gems
RUN apk update && apk add --no-cache build-base

# to be mounted externally
WORKDIR /mnt/src

# install the Gems needed by the blog
COPY src/* /mnt/src/
RUN bundle install

# make it available via port 4000
EXPOSE 4000
CMD ["bundle", "exec", "jekyll", "serve", "-w", "-l", "-H", "0.0.0.0"]
