---
name: Release

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Cache node modules
        uses: actions/cache@v4

        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ hashFiles('.release/package-lock.json') }}

      - name: Install dependencies
        run: npm --prefix .release/ ci

      - name: Release
        run: npx --prefix .release/ semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
