---
name: Release Test

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - release-dry-run

jobs:
  dry-release:
    name: Release dry-run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dry branch
        uses: actions/checkout@v3
        with:
          ref: release-dry-run

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"

      - name: Cache node modules
        uses: actions/cache@v3

        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ hashFiles('.release/package-lock.json') }}

      - name: Install dependencies
        run: npm --prefix .release/ ci

      - name: Dry run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: unset GITHUB_ACTIONS && npx --prefix .release/ semantic-release --dry-run --no-ci --debug
